### ISSUE TITLE
Cross-platform ECDH

### ISSUE THREAD

**Issue by c19x** [theheraldproject/herald-for-ios#136]
- Investigate options for cross-platform key exchange to enable implementation of secure payload

**Comment by adamfowleruk** [comment]
Key requirements for this payload versus other payload:-

- [ ] Prevent Replay Attack
- [ ] Prevent Relay Attack
- [ ] Prevent passive interception of exposure token exchanged between a pair of devices
- [ ] Key exchanged only used once even for the same pair of devices
- [ ] Factors used for key must not be fixed and must be non-trivial (So that only state actors (and not anyone with less resources) have the resources to potentially break them, centrally)

Things you probably won't be able to prevent:-
- [ ] Man in the middle attack (Because by necessity each pair of phones don't know the identity of each other)

Potential new name:-
- Epidecen (Epidemiological Decentralised payload) - like Epicentre, but not... (I'm bad at naming things, I know, 'Herald' itself was like the 58th name choice...)
